stages:
  data_ingestion:
    cmd: python src/emailClassifier/pipeline/data_ingestion_pipeline.py
    deps:
      - src/emailClassifier/components/data_ingestion.py
      - config/config.yaml
    outs:
      - output/data_ingestion/combined_data.csv


  data_validation:
    cmd: python src/emailClassifier/pipeline/data_validation_pipeline.py
    deps:
      - src/emailClassifier/components/data_validation.py
      - output/data_ingestion/combined_data.csv
      - config/config.yaml
    outs:
      - output/data_validation/status.txt


  data_transformation:
    cmd: python src/emailClassifier/pipeline/data_transform_pipeline.py
    deps: 
      - src/emailClassifier/components/data_transformation.py
      - output/data_ingestion/combined_data.csv
      - config/config.yaml
    outs:
      - output/data_transformation/x_train.pkl
      - output/data_transformation/x_val.pkl
      - output/data_transformation/y_train.pkl
      - output/data_transformation/y_val.pkl
      - output/data_transformation/vectorizer.pkl
  

  model_building:
    cmd: python src/emailClassifier/pipeline/model_build_pipeline.py
    deps:
      - src/emailClassifier/components/model_build.py
      - output/data_transformation/x_train.pkl
      - output/data_transformation/y_train.pkl
      - config/config.yaml
    params:
      - params.yaml:
          - SVC.C
          - SVC.kernel
          - SVC.gamma
    outs:
      - output/build_model/model.pkl
      - output/run_id.txt
  

  model_evaluation:
    cmd: python src/emailClassifier/pipeline/model_eval_pipeline.py
    deps:
      - src/emailClassifier/components/mode_eval.py
      - output/data_transformation/x_val.pkl
      - output/data_transformation/y_val.pkl
      - output/build_model/model.pkl
      - config/config.yaml
    metrics:
      - output/model_evaluation/mertic.json:
          cache: false